#!/bin/bash
[[ $EUID -ne 0 ]] && exec sudo -E "$0" "$@"

set -e
trap 'error_exit' ERR
INSTALLED=""

echo "Внимание: Для работы скрипта требуется стабильное интернет-соединение и ОС Debian 13 (trixie)"
read -p "Вы уверены, что хотите продолжить? (y/n): " confirm < /dev/tty

if [[ "$confirm" != "y" ]]; then
	echo "Выход из скрипта"
	exit
fi

check_package() {
	local package=$1

	if dpkg -l | grep -q "^ii  $package"; then
		echo "Пакет $package установлен"
		# INSTALLED="$INSTALLED $package"
		return 0
	else
		echo "Пакет $package не установлен"
		return 1
	fi
}

error_exit() {
    echo ""
    echo "Произошла ошибка"
    
    if [ -n "$INSTALLED" ]; then
		read -p "Хотите ли откатить изменения? (y/n): " confirmExit < /dev/tty
		if [ "$confirmExit" == "y" ]; then
			echo "Удаляю установленные пакеты: $INSTALLED"
			apt-get remove --purge -y $INSTALLED
		fi
    fi
    
    exit 1
}

manage_installed() {
    local package=$1
    local service=$2
    
    echo ""
    echo "Что вы хотите сделать с пакетом $package?"
    echo "1) Пропустить (оставить как есть)"
    echo "2) Переустановить пакет"
    echo "3) Удалить пакет"
    echo "4) Изменить конфигурацию"
    read -p "Выберите действие (1-4): " action < /dev/tty
    
    case $action in
        1)
            echo "Пропускаем $package"
            ;;
        2)
            echo "Переустанавливаю $package..."
            apt-get install --reinstall -y "$package"
            INSTALLED="$INSTALLED $package"
			systemctl restart "$service"
    		echo "$service перезапущен"
            ;;
        3)
            echo "Удаляю $package..."
            apt-get remove --purge -y "$package"
			echo $?
            ;;
        4)
            echo ""
			;;
        *)
            echo "Неверный выбор, пропускаем"
            ;;
    esac
	
}


echo "Проверка операционной системы..."
if cat /etc/os-release | grep -q 'VERSION="13 (trixie)"'; then
    echo "Это Debian Trixie"
else
    echo "Внимание: обнаружена другая ОС. Возможны ошибки."
    read -p "Вы уверены, что хотите продолжить? (y/n): " confirm < /dev/tty

    if [[ "$confirm" != "y" ]]; then
        echo "Выход из скрипта"
        exit
    fi
fi

echo "Проверка интернет-соединения..."
if ! ping -c 1 google.com &>/dev/null; then
    echo "Нет интернет-соединения!"
    exit 1
fi

apt-get update

if check_package "openssh-server"; then
	manage_installed "openssh-server" "ssh"
else
	apt-get -y install openssh-server=1:10.0p1-7+deb13u1
	# apt-get -y install openssh-server
	INSTALLED="$INSTALLED openssh-server"
    systemctl status ssh | grep -B 2 'active (running)'
fi


if check_package "nginx"; then
	manage_installed "nginx" "nginx"
else
	apt-get -y install nginx=1.26.3-3+deb13u2
	# apt-get -y install nginx
	INSTALLED="$INSTALLED nginx"
    systemctl status nginx | grep -B 2 'active (running)'
fi


if check_package "mariadb-server"; then
	manage_installed "mariadb-server" "mariadb"
else
	apt-get -y install mariadb-server=1:11.8.6-0+deb13u1
	# apt-get -y install mariadb-server
	INSTALLED="$INSTALLED mariadb-server"
    systemctl status mariadb | grep -B 2 'active (running)'
fi

if check_package "nodejs"; then
	# manage_installed "mariadb-server" "mariadb"
    echo "nodejs уже установлен"
else
    curl -sSL https://deb.nodesource.com/setup_20.x | bash
    sudo apt-get install -y nodejs
	INSTALLED="$INSTALLED nodejs"
fi

GITHUB_USER="Kveenfy"
REPOSITORY_NAME="deploy-website"
APP_DIR="/var/www/testapp"

mkdir -p "$APP_DIR"

for file in app.js dbSevice.js index.html package.json package-lock.json; do
    echo "Скачиваю $file"
    curl -s "https://raw.githubusercontent.com/$GITHUB_USER/$REPOSITORY_NAME/main/$file" -o "$APP_DIR/$file"
done

echo "Устанавливаю зависимости npm"
npm install --production -C "$APP_DIR"

echo "Настраиваю базу данных..."
mysql << EOF
CREATE DATABASE IF NOT EXISTS testdb;
CREATE USER IF NOT EXISTS 'nikitaroot'@'localhost' IDENTIFIED BY '1111';
GRANT ALL PRIVILEGES ON testdb.* TO 'nikitaroot'@'localhost';
FLUSH PRIVILEGES;
USE testdb;
CREATE TABLE IF NOT EXISTS users ( id int auto_increment primary key, name varchar(30) not null);
EOF

echo "База данных testdb и пользователь nikitaroot созданы"

echo "Создаю .env файл..."
cat > "$APP_DIR/.env" << EOF
PORT=8000
USER=nikitaroot
PASSWORD=1111
DATABASE=testdb
DB_PORT=3306
HOST=localhost
EOF

cat > /etc/nginx/sites-available/testapp << EOF
server {
    listen 80;
    server_name 192.168.1.7;

    location / {
        root /var/www/testapp;
        index index.html;
    }

    location /api/ {
        proxy_pass http://localhost:8000;
    }
}
EOF

ln -sf /etc/nginx/sites-available/testapp /etc/nginx/sites-enabled/
systemctl restart nginx

echo "Создаю службу автозагрузки..."
cat > /etc/systemd/system/testapp.service << EOF
[Unit]
Description=Node.js Test App
After=network.target mysql.service

[Service]
Type=simple
User=root
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/node app.js
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable testapp
systemctl restart testapp

echo "Сайт запущен и добавлен в автозагрузку!"